name: sqflite_tizen
description: Tizen implementation of the sqflite plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/sqflite
version: 0.2.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SqflitePlugin
        fileName: sqflite_plugin.h
        dartPluginClass: SqfliteTizen

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
