name: volume_controller_tizen
description: Tizen implementation of the volume_controller plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/volume_controller
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: VolumeControllerTizenPlugin
        fileName: volume_controller_tizen_plugin.h
