name: speech_to_text_tizen
description: Tizen implementation of the speech_to_text plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/speech_to_text
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: SpeechToTextTizenPlugin
        fileName: speech_to_text_tizen_plugin.h
